export default [
    {
        title:'Home',
        path:"home"
    },
    {
        title:'About',
        path:"about"
    },
    {
        title:'Skills',
        path:"skills"
    },
    {
        title:'Experiences',
        path:'experiences'
    },
    {
        title:'Portofolio',
        path:"portofolio"
    },
    {
        title:'Feedback',
        path:"feedback"
    }
];