import './globals.css';
import 'remixicon/fonts/remixicon.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';


export const metadata: Metadata = {
  title: 'Wendi | Portofolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">{children}</body>
    </html>
  )
}
