import "./globals.css";
import "remixicon/fonts/remixicon.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Wendi | Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1 , maximum-scale=1"
        />
      </head>
      <body className="overflow-x-hidden">{children}</body>
    </html>
  );
}
